version: "3.5"

services:
  api01: &api
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    build:
      context: .
    hostname: api01
    depends_on:
      - db
    # Não é necessário expor qualquer porta além da porta do load balancer,
    # mas é comum as pessoas o fazerem para testarem suas APIs e conectarem
    # ao banco de dados na fase de desenvolvimento.
    ports:
      - "8081:3000"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    ports:
      - "8082:3000"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
  db:
    image: postgres:latest
    hostname: db
    command: postgres -c log_min_messages=FATAL
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

# O uso do modo `bridge` deve ser adequado à carga que será usada no teste.
# A edição anterior se beneficiou do modo host pois o volume de requisições
# era relativamente alto e a virtualização da rede se tornou um gargalo, mas
# este modo é mais complexo de ser configurado. Fique à vontade para usar o
# modo que quiser desde que não conflite com portas trivialmente usadas em um
# SO.
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
